create extension if not exists pgcrypto;

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  city text not null default 'Quito',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#dbeafe',
  counts_hours boolean not null default true,
  active boolean not null default true
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  app_role text not null default 'supervisor'
    check (app_role in ('admin','supervisor')),
  location_id bigint references public.locations(id),
  active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.profile_locations (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  location_id bigint not null references public.locations(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(profile_id,location_id)
);

insert into public.profile_locations(profile_id,location_id)
select id,location_id from public.profiles where location_id is not null
on conflict do nothing;

create table if not exists public.supervisors (
  id bigint generated by default as identity primary key,
  name text not null,
  location_id bigint not null references public.locations(id),
  active boolean not null default true,
  active_from date not null default date '2026-07-27',
  active_until date,
  created_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  supervisor_id bigint not null references public.supervisors(id) on delete cascade,
  work_date date not null,
  start_time time,
  end_time time,
  role_id bigint not null references public.roles(id),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(supervisor_id, work_date)
);

alter table public.supervisors
  add column if not exists active_from date not null default date '2026-07-27';
alter table public.supervisors
  add column if not exists active_until date;
update public.supervisors s
set active_until=coalesce((select max(a.work_date) from public.assignments a where a.supervisor_id=s.id),s.active_from)
where s.active=false and s.active_until is null;

create table if not exists public.shopper_staff(
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check(category in ('purchase','delivery')),
  employment_type text not null default 'Interno',
  location_id bigint not null references public.locations(id),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.shopper_staff add column if not exists shopper_external_id text;
drop index if exists public.shopper_staff_external_id_unique;

create table if not exists public.shopper_shift_types(
  id bigint generated by default as identity primary key,
  code text not null,
  label text not null,
  start_time time,
  end_time time,
  category text not null default 'both' check(category in ('purchase','delivery','both')),
  location_id bigint references public.locations(id) on delete cascade,
  counts_opening boolean not null default false,
  counts_closing boolean not null default false,
  is_free boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.shopper_shift_types drop constraint if exists shopper_shift_types_code_key;
create unique index if not exists shopper_shift_types_scope_unique
on public.shopper_shift_types(coalesce(location_id,0),category,code);

create table if not exists public.shopper_turns(
  id bigint generated by default as identity primary key,
  staff_id bigint not null references public.shopper_staff(id) on delete cascade,
  work_date date not null,
  turn_code text not null check(turn_code in ('A','A2','B','T','I','N','L','V')),
  updated_at timestamptz not null default now(),
  unique(staff_id,work_date)
);
alter table public.shopper_turns drop constraint if exists shopper_turns_turn_code_check;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,full_name)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from profiles where id=auth.uid() and app_role='admin' and active);
$$;

create or replace function public.my_location()
returns bigint language sql stable security definer set search_path = public as $$
  select location_id from profiles where id=auth.uid() and active;
$$;

create or replace function public.has_location(target_location bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from profile_locations pl
    join profiles p on p.id=pl.profile_id
    where pl.profile_id=auth.uid() and pl.location_id=target_location and p.active
  );
$$;

alter table public.locations enable row level security;
alter table public.roles enable row level security;
alter table public.profiles enable row level security;
alter table public.profile_locations enable row level security;
alter table public.supervisors enable row level security;
alter table public.assignments enable row level security;
alter table public.shopper_staff enable row level security;
alter table public.shopper_shift_types enable row level security;
alter table public.shopper_turns enable row level security;

drop policy if exists locations_read on public.locations;
create policy locations_read on public.locations for select to authenticated
using (public.is_admin() or public.has_location(id));
drop policy if exists locations_admin on public.locations;
create policy locations_admin on public.locations for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles for select to authenticated using (active or public.is_admin());
drop policy if exists roles_admin on public.roles;
create policy roles_admin on public.roles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated
using (id=auth.uid() or public.is_admin());
drop policy if exists profiles_admin on public.profiles;
create policy profiles_admin on public.profiles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists profile_locations_read on public.profile_locations;
create policy profile_locations_read on public.profile_locations for select to authenticated
using (profile_id=auth.uid() or public.is_admin());
drop policy if exists profile_locations_admin on public.profile_locations;
create policy profile_locations_admin on public.profile_locations for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists supervisors_read on public.supervisors;
create policy supervisors_read on public.supervisors for select to authenticated
using (public.is_admin() or public.has_location(location_id));
drop policy if exists supervisors_admin on public.supervisors;
create policy supervisors_admin on public.supervisors for all to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists supervisors_assigned_write on public.supervisors;
create policy supervisors_assigned_write on public.supervisors for all to authenticated
using (public.has_location(location_id))
with check (public.has_location(location_id));

drop policy if exists assignments_read on public.assignments;
create policy assignments_read on public.assignments for select to authenticated
using (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or public.has_location(s.location_id))));
drop policy if exists assignments_write on public.assignments;
create policy assignments_write on public.assignments for all to authenticated
using (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or public.has_location(s.location_id))))
with check (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or public.has_location(s.location_id))));

drop policy if exists shopper_staff_access on public.shopper_staff;
create policy shopper_staff_access on public.shopper_staff for all to authenticated
using(public.is_admin() or public.has_location(location_id))
with check(public.is_admin() or public.has_location(location_id));

drop policy if exists shopper_shift_types_access on public.shopper_shift_types;
create policy shopper_shift_types_access on public.shopper_shift_types for all to authenticated
using(public.is_admin() or location_id is null or public.has_location(location_id))
with check(public.is_admin() or (location_id is not null and public.has_location(location_id)));

drop policy if exists shopper_turns_access on public.shopper_turns;
create policy shopper_turns_access on public.shopper_turns for all to authenticated
using(exists(select 1 from public.shopper_staff s where s.id=staff_id
  and (public.is_admin() or public.has_location(s.location_id))))
with check(exists(select 1 from public.shopper_staff s where s.id=staff_id
  and (public.is_admin() or public.has_location(s.location_id))));

insert into public.shopper_shift_types(code,label,start_time,end_time,category,counts_opening,counts_closing,is_free) values
('A','Apertura','06:00','14:00','both',true,false,false),
('A2','Apertura 2','07:00','15:00','both',true,false,false),
('B','Intermedio','10:00','18:00','both',false,false,false),
('T','Apertura y cierre','13:00','21:00','both',true,true,false),
('I','Apertura','06:00','14:00','both',true,false,false),
('N','Apertura','06:00','14:00','both',true,false,false),
('L','Libre',null,null,'both',false,false,true),
('V','Vacaciones',null,null,'both',false,false,true)
on conflict do nothing;

insert into public.locations(name,city) values
('MX. Village Plaza','Guayaquil'),('SX. Plaza Batán','Guayaquil'),
('SX. Villa Club','Guayaquil'),('MX. Ceibos','Guayaquil'),
('SX. Ciudad Celeste','Guayaquil'),('MX. City Mall','Guayaquil'),
('MX. Mall del Sol','Guayaquil'),('SX. Vistana','Guayaquil'),
('SX. Vía a la Costa','Guayaquil'),('MX. Mall del Norte','Guayaquil'),
('MX. Mall del Sur','Guayaquil'),('Akí Astillero','Guayaquil'),
('Akí Mapasingue','Guayaquil'),('Akí La Joya','Guayaquil'),
('MX. Wayra','Cuenca'),('SX. Vergel','Cuenca'),('SX. Don Bosco','Cuenca'),
('SX. Chaullabamba','Cuenca'),('Super Akí Narancay','Cuenca'),
('SX. Pradera','Cuenca'),('MX. Mall del Pacífico','Manta'),
('Supermaxi Salinas','Salinas'),('Akí Pedernales','Pedernales')
on conflict (name) do nothing;

insert into public.roles(name,color,counts_hours) values
('Compra / Procesos','#dcfce7',true),
('Certificaciones / Grupos','#dbeafe',true),
('Shopper','#f3e8ff',true),
('Libre','#fef3c7',false),
('Total','#e0f2fe',true),
('Vacaciones','#fee2e2',false)
on conflict (name) do nothing;

insert into public.supervisors(name,location_id)
select v.name,l.id from (values ('Axel'),('Gia'),('Henry'),('Jean C.'),('Viviana'),('Melany')) v(name)
cross join lateral (select id from public.locations where name='MX. Village Plaza') l
where not exists(select 1 from public.supervisors s where s.name=v.name and s.location_id=l.id);

create table if not exists public.administrator_evaluations (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete restrict,
  week_start date not null,
  week_end date not null,
  visit_date date not null,
  next_visit_date date,
  administrator_name text not null check (length(trim(administrator_name)) between 2 and 160),
  administrator_position text not null default '',
  administrator_phone text not null default '',
  metrics_socialized boolean not null default false,
  rule_compliance boolean,
  uniform_compliance boolean,
  ethics_compliance boolean,
  punctuality_compliance boolean,
  no_team_complaints boolean,
  particular_observations text not null default '',
  observations text not null default '',
  local_feedback text not null default '',
  supervisor_feedback text not null default '',
  submitted_by uuid not null,
  submitted_by_name text not null,
  submitted_by_email text not null,
  last_updated_by uuid not null,
  last_updated_by_name text not null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint administrator_evaluations_location_week_key unique (location_id, week_start),
  constraint administrator_evaluations_week_monday_check check (extract(isodow from week_start) = 1),
  constraint administrator_evaluations_week_end_check check (week_end = week_start + 6),
  constraint administrator_evaluations_visit_week_check check (visit_date between week_start and week_end),
  constraint administrator_evaluations_next_visit_check check (next_visit_date is null or next_visit_date >= visit_date)
);
create index if not exists administrator_evaluations_week_location_idx on public.administrator_evaluations (week_start, location_id);
create index if not exists administrator_evaluations_submitter_week_idx on public.administrator_evaluations (submitted_by, week_start desc);

create table if not exists public.administrator_evaluation_results (
  evaluation_id bigint primary key references public.administrator_evaluations(id) on delete cascade,
  compliant_count smallint not null check (compliant_count between 0 and 5),
  applicable_count smallint not null check (applicable_count between 1 and 5),
  score numeric(5,2) not null check (score between 0 and 100),
  semaphore text not null check (semaphore in ('green','yellow','red')),
  calculated_at timestamptz not null default now()
);

alter table public.administrator_evaluations enable row level security;
alter table public.administrator_evaluation_results enable row level security;
revoke all on table public.administrator_evaluations from anon, authenticated;
revoke all on table public.administrator_evaluation_results from anon, authenticated;
revoke all on sequence public.administrator_evaluations_id_seq from anon, authenticated;
grant select on table public.administrator_evaluations to authenticated;
drop policy if exists administrator_evaluations_read on public.administrator_evaluations;
create policy administrator_evaluations_read on public.administrator_evaluations for select to authenticated
using (public.is_admin() or public.has_location(location_id));
drop policy if exists administrator_evaluation_results_admin_read on public.administrator_evaluation_results;
create policy administrator_evaluation_results_admin_read on public.administrator_evaluation_results for select to authenticated
using (public.is_admin());

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
create or replace function private.prepare_administrator_evaluation()
returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare actor_id uuid:=(select auth.uid());actor_name text;actor_email text;
begin
  if actor_id is null then raise exception 'Sesión no válida.' using errcode='42501';end if;
  select coalesce(nullif(trim(full_name),''),email),email into actor_name,actor_email from public.profiles where id=actor_id and active;
  if actor_email is null then raise exception 'Usuario no autorizado.' using errcode='42501';end if;
  if tg_op='INSERT' then new.submitted_by:=actor_id;new.submitted_by_name:=actor_name;new.submitted_by_email:=actor_email;new.submitted_at:=now();
  else new.location_id:=old.location_id;new.week_start:=old.week_start;new.week_end:=old.week_end;new.submitted_by:=old.submitted_by;new.submitted_by_name:=old.submitted_by_name;new.submitted_by_email:=old.submitted_by_email;new.submitted_at:=old.submitted_at;end if;
  new.last_updated_by:=actor_id;new.last_updated_by_name:=actor_name;new.updated_at:=now();return new;
end;$$;
revoke all on function private.prepare_administrator_evaluation() from public,anon,authenticated;
create or replace function private.calculate_administrator_evaluation_result()
returns trigger language plpgsql security definer set search_path=pg_catalog,public,private as $$
declare applicable smallint;compliant smallint;calculated_score numeric(5,2);calculated_semaphore text;
begin
  applicable:=(case when new.rule_compliance is null then 0 else 1 end)+(case when new.uniform_compliance is null then 0 else 1 end)+(case when new.ethics_compliance is null then 0 else 1 end)+(case when new.punctuality_compliance is null then 0 else 1 end)+(case when new.no_team_complaints is null then 0 else 1 end);
  compliant:=(case when new.rule_compliance is true then 1 else 0 end)+(case when new.uniform_compliance is true then 1 else 0 end)+(case when new.ethics_compliance is true then 1 else 0 end)+(case when new.punctuality_compliance is true then 1 else 0 end)+(case when new.no_team_complaints is true then 1 else 0 end);
  if applicable<1 then raise exception 'Al menos un criterio debe ser aplicable.' using errcode='23514';end if;
  calculated_score:=round(compliant::numeric/applicable::numeric*100,2);calculated_semaphore:=case when calculated_score>=90 then 'green' when calculated_score>=75 then 'yellow' else 'red' end;
  insert into public.administrator_evaluation_results(evaluation_id,compliant_count,applicable_count,score,semaphore,calculated_at) values(new.id,compliant,applicable,calculated_score,calculated_semaphore,now()) on conflict(evaluation_id) do update set compliant_count=excluded.compliant_count,applicable_count=excluded.applicable_count,score=excluded.score,semaphore=excluded.semaphore,calculated_at=excluded.calculated_at;return new;
end;$$;
revoke all on function private.calculate_administrator_evaluation_result() from public,anon,authenticated;
drop trigger if exists prepare_administrator_evaluation on public.administrator_evaluations;
create trigger prepare_administrator_evaluation before insert or update on public.administrator_evaluations for each row execute function private.prepare_administrator_evaluation();
drop trigger if exists calculate_administrator_evaluation_result on public.administrator_evaluations;
create trigger calculate_administrator_evaluation_result after insert or update on public.administrator_evaluations for each row execute function private.calculate_administrator_evaluation_result();
grant select,insert,update on table public.administrator_evaluations to authenticated;
grant usage,select on sequence public.administrator_evaluations_id_seq to authenticated;
grant select on table public.administrator_evaluation_results to authenticated;
drop policy if exists administrator_evaluations_insert on public.administrator_evaluations;
create policy administrator_evaluations_insert on public.administrator_evaluations for insert to authenticated with check(submitted_by=(select auth.uid()) and (public.is_admin() or public.has_location(location_id)));
drop policy if exists administrator_evaluations_update on public.administrator_evaluations;
create policy administrator_evaluations_update on public.administrator_evaluations for update to authenticated using(public.is_admin() or public.has_location(location_id)) with check(public.is_admin() or public.has_location(location_id));
