create extension if not exists pgcrypto;

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  city text not null default 'Quito',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#dbeafe',
  counts_hours boolean not null default true,
  active boolean not null default true
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  app_role text not null default 'supervisor'
    check (app_role in ('admin','supervisor')),
  location_id bigint references public.locations(id),
  active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.supervisors (
  id bigint generated by default as identity primary key,
  name text not null,
  location_id bigint not null references public.locations(id),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  supervisor_id bigint not null references public.supervisors(id) on delete cascade,
  work_date date not null,
  start_time time,
  end_time time,
  role_id bigint not null references public.roles(id),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(supervisor_id, work_date)
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,full_name)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from profiles where id=auth.uid() and app_role='admin' and active);
$$;

create or replace function public.my_location()
returns bigint language sql stable security definer set search_path = public as $$
  select location_id from profiles where id=auth.uid() and active;
$$;

alter table public.locations enable row level security;
alter table public.roles enable row level security;
alter table public.profiles enable row level security;
alter table public.supervisors enable row level security;
alter table public.assignments enable row level security;

drop policy if exists locations_read on public.locations;
create policy locations_read on public.locations for select to authenticated
using (public.is_admin() or id=public.my_location());
drop policy if exists locations_admin on public.locations;
create policy locations_admin on public.locations for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles for select to authenticated using (active or public.is_admin());
drop policy if exists roles_admin on public.roles;
create policy roles_admin on public.roles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated
using (id=auth.uid() or public.is_admin());
drop policy if exists profiles_admin on public.profiles;
create policy profiles_admin on public.profiles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists supervisors_read on public.supervisors;
create policy supervisors_read on public.supervisors for select to authenticated
using (public.is_admin() or location_id=public.my_location());
drop policy if exists supervisors_admin on public.supervisors;
create policy supervisors_admin on public.supervisors for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists assignments_read on public.assignments;
create policy assignments_read on public.assignments for select to authenticated
using (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or s.location_id=public.my_location())));
drop policy if exists assignments_write on public.assignments;
create policy assignments_write on public.assignments for all to authenticated
using (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or s.location_id=public.my_location())))
with check (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or s.location_id=public.my_location())));

insert into public.locations(name,city) values
('Village Plaza','Quito'),('El Recreo','Quito'),('El Bosque','Quito'),
('Quicentro Sur','Quito'),('Quicentro Shopping','Quito'),
('Scala Shopping','Quito'),('Condado Shopping','Quito')
on conflict (name) do nothing;

insert into public.roles(name,color,counts_hours) values
('Compra / Procesos','#dcfce7',true),
('Certificaciones / Grupos','#dbeafe',true),
('Shopper','#f3e8ff',true),
('Libre','#fef3c7',false),
('Total','#e0f2fe',true),
('Vacaciones','#fee2e2',false)
on conflict (name) do nothing;

insert into public.supervisors(name,location_id)
select v.name,l.id from (values ('Axel'),('Gia'),('Henry'),('Jean C.'),('Viviana'),('Melany')) v(name)
cross join lateral (select id from public.locations where name='Village Plaza') l
where not exists(select 1 from public.supervisors s where s.name=v.name and s.location_id=l.id);
