create extension if not exists pgcrypto;

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  city text not null default 'Quito',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#dbeafe',
  counts_hours boolean not null default true,
  active boolean not null default true
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  app_role text not null default 'supervisor'
    check (app_role in ('admin','supervisor')),
  location_id bigint references public.locations(id),
  active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.profile_locations (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  location_id bigint not null references public.locations(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(profile_id,location_id)
);

insert into public.profile_locations(profile_id,location_id)
select id,location_id from public.profiles where location_id is not null
on conflict do nothing;

create table if not exists public.supervisors (
  id bigint generated by default as identity primary key,
  name text not null,
  location_id bigint not null references public.locations(id),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  supervisor_id bigint not null references public.supervisors(id) on delete cascade,
  work_date date not null,
  start_time time,
  end_time time,
  role_id bigint not null references public.roles(id),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(supervisor_id, work_date)
);

create table if not exists public.shopper_staff(
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null check(category in ('purchase','delivery')),
  employment_type text not null default 'Interno',
  location_id bigint not null references public.locations(id),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.shopper_staff add column if not exists shopper_external_id text;
drop index if exists public.shopper_staff_external_id_unique;

create table if not exists public.shopper_shift_types(
  id bigint generated by default as identity primary key,
  code text not null,
  label text not null,
  start_time time,
  end_time time,
  category text not null default 'both' check(category in ('purchase','delivery','both')),
  location_id bigint references public.locations(id) on delete cascade,
  counts_opening boolean not null default false,
  counts_closing boolean not null default false,
  is_free boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists shopper_shift_types_scope_unique
on public.shopper_shift_types(coalesce(location_id,0),category,code);

create table if not exists public.shopper_turns(
  id bigint generated by default as identity primary key,
  staff_id bigint not null references public.shopper_staff(id) on delete cascade,
  work_date date not null,
  turn_code text not null check(turn_code in ('A','A2','B','T','I','N','L','V')),
  updated_at timestamptz not null default now(),
  unique(staff_id,work_date)
);
alter table public.shopper_turns drop constraint if exists shopper_turns_turn_code_check;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,full_name)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from profiles where id=auth.uid() and app_role='admin' and active);
$$;

create or replace function public.my_location()
returns bigint language sql stable security definer set search_path = public as $$
  select location_id from profiles where id=auth.uid() and active;
$$;

create or replace function public.has_location(target_location bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(
    select 1 from profile_locations pl
    join profiles p on p.id=pl.profile_id
    where pl.profile_id=auth.uid() and pl.location_id=target_location and p.active
  );
$$;

alter table public.locations enable row level security;
alter table public.roles enable row level security;
alter table public.profiles enable row level security;
alter table public.profile_locations enable row level security;
alter table public.supervisors enable row level security;
alter table public.assignments enable row level security;
alter table public.shopper_staff enable row level security;
alter table public.shopper_shift_types enable row level security;
alter table public.shopper_turns enable row level security;

drop policy if exists locations_read on public.locations;
create policy locations_read on public.locations for select to authenticated
using (public.is_admin() or public.has_location(id));
drop policy if exists locations_admin on public.locations;
create policy locations_admin on public.locations for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles for select to authenticated using (active or public.is_admin());
drop policy if exists roles_admin on public.roles;
create policy roles_admin on public.roles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated
using (id=auth.uid() or public.is_admin());
drop policy if exists profiles_admin on public.profiles;
create policy profiles_admin on public.profiles for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists profile_locations_read on public.profile_locations;
create policy profile_locations_read on public.profile_locations for select to authenticated
using (profile_id=auth.uid() or public.is_admin());
drop policy if exists profile_locations_admin on public.profile_locations;
create policy profile_locations_admin on public.profile_locations for all to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists supervisors_read on public.supervisors;
create policy supervisors_read on public.supervisors for select to authenticated
using (public.is_admin() or public.has_location(location_id));
drop policy if exists supervisors_admin on public.supervisors;
create policy supervisors_admin on public.supervisors for all to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists supervisors_assigned_write on public.supervisors;
create policy supervisors_assigned_write on public.supervisors for all to authenticated
using (public.has_location(location_id))
with check (public.has_location(location_id));

drop policy if exists assignments_read on public.assignments;
create policy assignments_read on public.assignments for select to authenticated
using (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or public.has_location(s.location_id))));
drop policy if exists assignments_write on public.assignments;
create policy assignments_write on public.assignments for all to authenticated
using (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or public.has_location(s.location_id))))
with check (exists(select 1 from supervisors s where s.id=supervisor_id
  and (public.is_admin() or public.has_location(s.location_id))));

drop policy if exists shopper_staff_access on public.shopper_staff;
create policy shopper_staff_access on public.shopper_staff for all to authenticated
using(public.is_admin() or public.has_location(location_id))
with check(public.is_admin() or public.has_location(location_id));

drop policy if exists shopper_shift_types_access on public.shopper_shift_types;
create policy shopper_shift_types_access on public.shopper_shift_types for all to authenticated
using(public.is_admin() or location_id is null or public.has_location(location_id))
with check(public.is_admin() or (location_id is not null and public.has_location(location_id)));

drop policy if exists shopper_turns_access on public.shopper_turns;
create policy shopper_turns_access on public.shopper_turns for all to authenticated
using(exists(select 1 from public.shopper_staff s where s.id=staff_id
  and (public.is_admin() or public.has_location(s.location_id))))
with check(exists(select 1 from public.shopper_staff s where s.id=staff_id
  and (public.is_admin() or public.has_location(s.location_id))));

insert into public.shopper_shift_types(code,label,start_time,end_time,category,counts_opening,counts_closing,is_free) values
('A','Apertura','06:00','14:00','both',true,false,false),
('A2','Apertura 2','07:00','15:00','both',true,false,false),
('B','Intermedio','10:00','18:00','both',false,false,false),
('T','Apertura y cierre','13:00','21:00','both',true,true,false),
('I','Apertura','06:00','14:00','both',true,false,false),
('N','Apertura','06:00','14:00','both',true,false,false),
('L','Libre',null,null,'both',false,false,true),
('V','Vacaciones',null,null,'both',false,false,true)
on conflict do nothing;

insert into public.locations(name,city) values
('MX. Village Plaza','Guayaquil'),('SX. Plaza Batán','Guayaquil'),
('SX. Villa Club','Guayaquil'),('MX. Ceibos','Guayaquil'),
('SX. Ciudad Celeste','Guayaquil'),('MX. City Mall','Guayaquil'),
('MX. Mall del Sol','Guayaquil'),('SX. Vistana','Guayaquil'),
('SX. Vía a la Costa','Guayaquil'),('MX. Mall del Norte','Guayaquil'),
('MX. Mall del Sur','Guayaquil'),('Akí Astillero','Guayaquil'),
('Akí Mapasingue','Guayaquil'),('Akí La Joya','Guayaquil'),
('MX. Wayra','Cuenca'),('SX. Vergel','Cuenca'),('SX. Don Bosco','Cuenca'),
('SX. Chaullabamba','Cuenca'),('Super Akí Narancay','Cuenca'),
('SX. Pradera','Cuenca'),('MX. Mall del Pacífico','Manta'),
('Supermaxi Salinas','Salinas'),('Akí Pedernales','Pedernales')
on conflict (name) do nothing;

insert into public.roles(name,color,counts_hours) values
('Compra / Procesos','#dcfce7',true),
('Certificaciones / Grupos','#dbeafe',true),
('Shopper','#f3e8ff',true),
('Libre','#fef3c7',false),
('Total','#e0f2fe',true),
('Vacaciones','#fee2e2',false)
on conflict (name) do nothing;

insert into public.supervisors(name,location_id)
select v.name,l.id from (values ('Axel'),('Gia'),('Henry'),('Jean C.'),('Viviana'),('Melany')) v(name)
cross join lateral (select id from public.locations where name='MX. Village Plaza') l
where not exists(select 1 from public.supervisors s where s.name=v.name and s.location_id=l.id);
