alter table public.shopper_staff
add column if not exists shopper_external_id text;

drop index if exists public.shopper_staff_external_id_unique;

create table if not exists public.shopper_shift_types(
  id bigint generated by default as identity primary key,
  code text not null,
  label text not null,
  start_time time,
  end_time time,
  category text not null default 'both'
    check(category in ('purchase','delivery','both')),
  location_id bigint references public.locations(id) on delete cascade,
  counts_opening boolean not null default false,
  counts_closing boolean not null default false,
  is_free boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists shopper_shift_types_scope_unique
on public.shopper_shift_types(coalesce(location_id,0),category,code);

alter table public.shopper_turns
drop constraint if exists shopper_turns_turn_code_check;

alter table public.shopper_shift_types enable row level security;

drop policy if exists shopper_shift_types_access on public.shopper_shift_types;
create policy shopper_shift_types_access
on public.shopper_shift_types for all to authenticated
using(public.is_admin() or location_id is null or public.has_location(location_id))
with check(public.is_admin() or (location_id is not null and public.has_location(location_id)));

insert into public.shopper_shift_types
(code,label,start_time,end_time,category,counts_opening,counts_closing,is_free)
values
('A','Apertura','06:00','14:00','both',true,false,false),
('A2','Apertura 2','07:00','15:00','both',true,false,false),
('B','Intermedio','10:00','18:00','both',false,false,false),
('T','Apertura y cierre','13:00','21:00','both',true,true,false),
('I','Apertura','06:00','14:00','both',true,false,false),
('N','Apertura','06:00','14:00','both',true,false,false),
('L','Libre',null,null,'both',false,false,true),
('V','Vacaciones',null,null,'both',false,false,true)
on conflict do nothing;
