create schema if not exists private;
revoke all on schema private from public, anon, authenticated;
grant usage on schema private to authenticated;

create or replace function private.is_active_user()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists(
    select 1 from public.profiles
    where id=(select auth.uid()) and active
  );
$$;
revoke all on function private.is_active_user() from public, anon;
grant execute on function private.is_active_user() to authenticated;

-- Los roles se retiran de forma lógica para no romper horarios históricos.
alter table public.roles add column if not exists updated_at timestamptz not null default now();
alter table public.roles add column if not exists updated_by uuid;
alter table public.roles add column if not exists updated_by_name text not null default '';
alter table public.roles add column if not exists archived_at timestamptz;

drop policy if exists roles_read on public.roles;
drop policy if exists roles_admin on public.roles;
drop policy if exists roles_active_users_insert on public.roles;
drop policy if exists roles_active_users_update on public.roles;
create policy roles_read on public.roles for select to authenticated
using (private.is_active_user());
create policy roles_active_users_insert on public.roles for insert to authenticated
with check (private.is_active_user());
create policy roles_active_users_update on public.roles for update to authenticated
using (private.is_active_user()) with check (private.is_active_user());
grant select,insert,update on table public.roles to authenticated;
grant usage,select on sequence public.roles_id_seq to authenticated;
revoke delete on table public.roles from authenticated;

create or replace function private.audit_role_change()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor uuid := (select auth.uid());
  actor_name text;
begin
  select coalesce(nullif(trim(full_name),''),email)
  into actor_name from public.profiles where id=actor and active;
  if actor_name is null then
    raise exception 'Usuario no autorizado.' using errcode='42501';
  end if;
  new.updated_by:=actor;
  new.updated_by_name:=actor_name;
  new.updated_at:=now();
  if old.active and not new.active then new.archived_at:=now(); end if;
  if not old.active and new.active then new.archived_at:=null; end if;
  return new;
end;
$$;
revoke all on function private.audit_role_change() from public, anon, authenticated;
drop trigger if exists audit_role_change on public.roles;
create trigger audit_role_change before update on public.roles
for each row execute function private.audit_role_change();

create table if not exists public.authorization_requests (
  id bigint generated by default as identity primary key,
  request_type text not null check (request_type in ('discount','incentive')),
  location_id bigint not null references public.locations(id) on delete restrict,
  location_name_snapshot text not null,
  shopper_name text not null check (length(trim(shopper_name)) between 2 and 180),
  shopper_external_id text not null default '',
  order_number text not null check (length(trim(order_number)) between 2 and 80),
  client_name text not null check (length(trim(client_name)) between 2 and 180),
  amount numeric(12,2) not null check (amount > 0 and amount <= 999999.99),
  reason text not null check (length(trim(reason)) between 5 and 4000),
  evidence_path text not null check (length(trim(evidence_path)) between 5 and 500),
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  decision_comment text not null default '',
  created_by uuid not null,
  created_by_name text not null,
  created_by_email text not null,
  created_at timestamptz not null default now(),
  decided_by uuid,
  decided_by_name text,
  decided_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint authorization_decision_check check (
    (status='pending' and decided_by is null and decided_at is null)
    or (status in ('approved','rejected') and decided_by is not null and decided_at is not null)
  )
);
create index if not exists authorization_requests_location_created_idx
  on public.authorization_requests (location_id, created_at desc);
create index if not exists authorization_requests_status_created_idx
  on public.authorization_requests (status, created_at desc);
create index if not exists authorization_requests_monthly_approved_idx
  on public.authorization_requests (location_id, request_type, created_at)
  where status='approved';

alter table public.authorization_requests enable row level security;
grant select,insert,update on table public.authorization_requests to authenticated;
grant usage,select on sequence public.authorization_requests_id_seq to authenticated;

drop policy if exists authorization_requests_read on public.authorization_requests;
create policy authorization_requests_read on public.authorization_requests for select to authenticated
using (public.is_admin() or public.has_location(location_id));
drop policy if exists authorization_requests_insert on public.authorization_requests;
create policy authorization_requests_insert on public.authorization_requests for insert to authenticated
with check (
  created_by=(select auth.uid())
  and status='pending'
  and (public.is_admin() or public.has_location(location_id))
);
drop policy if exists authorization_requests_admin_update on public.authorization_requests;
create policy authorization_requests_admin_update on public.authorization_requests for update to authenticated
using (public.is_admin()) with check (public.is_admin());

create or replace function private.protect_authorization_request()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor uuid := (select auth.uid());
  actor_name text;
  actor_email text;
  local_name text;
  actor_is_admin boolean;
begin
  select coalesce(nullif(trim(full_name),''),email),email,app_role='admin'
  into actor_name,actor_email,actor_is_admin
  from public.profiles where id=actor and active;
  if actor_email is null then raise exception 'Usuario no autorizado.' using errcode='42501'; end if;

  if tg_op='INSERT' then
    select name into local_name from public.locations where id=new.location_id and active;
    if local_name is null then raise exception 'Local no disponible.' using errcode='23514'; end if;
    new.location_name_snapshot:=local_name;
    new.created_by:=actor;
    new.created_by_name:=actor_name;
    new.created_by_email:=actor_email;
    new.created_at:=now();
    new.status:='pending';
    new.decision_comment:='';
    new.decided_by:=null;
    new.decided_by_name:=null;
    new.decided_at:=null;
  else
    if not actor_is_admin then raise exception 'Solo el administrador puede decidir solicitudes.' using errcode='42501'; end if;
    new.request_type:=old.request_type;
    new.location_id:=old.location_id;
    new.location_name_snapshot:=old.location_name_snapshot;
    new.shopper_name:=old.shopper_name;
    new.shopper_external_id:=old.shopper_external_id;
    new.order_number:=old.order_number;
    new.client_name:=old.client_name;
    new.amount:=old.amount;
    new.reason:=old.reason;
    new.evidence_path:=old.evidence_path;
    new.created_by:=old.created_by;
    new.created_by_name:=old.created_by_name;
    new.created_by_email:=old.created_by_email;
    new.created_at:=old.created_at;
    if new.status='pending' then
      new.decided_by:=null; new.decided_by_name:=null; new.decided_at:=null;
    else
      new.decided_by:=actor; new.decided_by_name:=actor_name; new.decided_at:=now();
    end if;
  end if;
  new.updated_at:=now();
  return new;
end;
$$;
revoke all on function private.protect_authorization_request() from public, anon, authenticated;
drop trigger if exists protect_authorization_request on public.authorization_requests;
create trigger protect_authorization_request before insert or update on public.authorization_requests
for each row execute function private.protect_authorization_request();

create table if not exists public.weekly_activity_submissions (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete restrict,
  location_name_snapshot text not null,
  week_start date not null,
  week_end date not null,
  activity_type text not null check (activity_type in ('shopper_purchase','shopper_delivery','supervisor_schedule')),
  submitted_by uuid not null,
  submitted_by_name text not null,
  submitted_by_email text not null,
  submitted_at timestamptz not null default now(),
  last_updated_by uuid not null,
  last_updated_by_name text not null,
  updated_at timestamptz not null default now(),
  unique (location_id, week_start, activity_type),
  constraint weekly_activity_monday_check check (extract(isodow from week_start)=1),
  constraint weekly_activity_end_check check (week_end=week_start+6)
);
create index if not exists weekly_activity_week_location_idx
  on public.weekly_activity_submissions (week_start desc, location_id);
create index if not exists weekly_activity_submitter_idx
  on public.weekly_activity_submissions (submitted_by, week_start desc);
alter table public.weekly_activity_submissions enable row level security;
grant select,insert,update on table public.weekly_activity_submissions to authenticated;
grant usage,select on sequence public.weekly_activity_submissions_id_seq to authenticated;

drop policy if exists weekly_activity_read on public.weekly_activity_submissions;
create policy weekly_activity_read on public.weekly_activity_submissions for select to authenticated
using (public.is_admin() or public.has_location(location_id));
drop policy if exists weekly_activity_insert on public.weekly_activity_submissions;
create policy weekly_activity_insert on public.weekly_activity_submissions for insert to authenticated
with check (submitted_by=(select auth.uid()) and (public.is_admin() or public.has_location(location_id)));
drop policy if exists weekly_activity_update on public.weekly_activity_submissions;
create policy weekly_activity_update on public.weekly_activity_submissions for update to authenticated
using (public.is_admin() or public.has_location(location_id))
with check (public.is_admin() or public.has_location(location_id));

create or replace function private.audit_weekly_activity()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor uuid := (select auth.uid());
  actor_name text;
  actor_email text;
  local_name text;
begin
  select coalesce(nullif(trim(full_name),''),email),email
  into actor_name,actor_email from public.profiles where id=actor and active;
  if actor_email is null then raise exception 'Usuario no autorizado.' using errcode='42501'; end if;
  if tg_op='INSERT' then
    select name into local_name from public.locations where id=new.location_id and active;
    if local_name is null then raise exception 'Local no disponible.' using errcode='23514'; end if;
    new.location_name_snapshot:=local_name;
    new.submitted_by:=actor;
    new.submitted_by_name:=actor_name;
    new.submitted_by_email:=actor_email;
    new.submitted_at:=now();
  else
    new.location_id:=old.location_id;
    new.location_name_snapshot:=old.location_name_snapshot;
    new.week_start:=old.week_start;
    new.week_end:=old.week_end;
    new.activity_type:=old.activity_type;
    new.submitted_by:=old.submitted_by;
    new.submitted_by_name:=old.submitted_by_name;
    new.submitted_by_email:=old.submitted_by_email;
    new.submitted_at:=old.submitted_at;
  end if;
  new.last_updated_by:=actor;
  new.last_updated_by_name:=actor_name;
  new.updated_at:=now();
  return new;
end;
$$;
revoke all on function private.audit_weekly_activity() from public, anon, authenticated;
drop trigger if exists audit_weekly_activity on public.weekly_activity_submissions;
create trigger audit_weekly_activity before insert or update on public.weekly_activity_submissions
for each row execute function private.audit_weekly_activity();

-- Evidencias privadas. El nombre inicia con el UUID del usuario que sube el archivo.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('authorization-evidence','authorization-evidence',false,8388608,array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set
  public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists authorization_evidence_insert on storage.objects;
create policy authorization_evidence_insert on storage.objects for insert to authenticated
with check (
  bucket_id='authorization-evidence'
  and (storage.foldername(name))[1]=(select auth.uid())::text
  and private.is_active_user()
);
drop policy if exists authorization_evidence_select on storage.objects;
create policy authorization_evidence_select on storage.objects for select to authenticated
using (
  bucket_id='authorization-evidence'
  and (
    owner_id=(select auth.uid())::text
    or public.is_admin()
    or exists (
      select 1 from public.authorization_requests request
      where request.evidence_path=name and public.has_location(request.location_id)
    )
  )
);
