create table if not exists public.weekly_evidences (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete restrict,
  location_name_snapshot text not null,
  week_start date not null,
  week_end date not null,
  evidence_type text not null check (evidence_type in ('automatic_assignment','team_meeting')),
  evidence_path text not null check (length(trim(evidence_path)) between 10 and 500),
  submitted_by uuid not null,
  submitted_by_name text not null,
  submitted_by_email text not null,
  submitted_at timestamptz not null default now(),
  last_updated_by uuid not null,
  last_updated_by_name text not null,
  updated_at timestamptz not null default now(),
  unique (location_id, week_start, evidence_type),
  constraint weekly_evidences_monday_check check (extract(isodow from week_start)=1),
  constraint weekly_evidences_end_check check (week_end=week_start+6)
);

create index if not exists weekly_evidences_week_location_idx
  on public.weekly_evidences (week_start desc, location_id);
create index if not exists weekly_evidences_submitter_idx
  on public.weekly_evidences (submitted_by, week_start desc);

alter table public.weekly_evidences enable row level security;
grant select,insert,update on table public.weekly_evidences to authenticated;
grant usage,select on sequence public.weekly_evidences_id_seq to authenticated;
revoke delete on table public.weekly_evidences from authenticated;

drop policy if exists weekly_evidences_read on public.weekly_evidences;
create policy weekly_evidences_read on public.weekly_evidences for select to authenticated
using (public.is_admin() or public.has_location(location_id));

drop policy if exists weekly_evidences_insert on public.weekly_evidences;
create policy weekly_evidences_insert on public.weekly_evidences for insert to authenticated
with check (
  submitted_by=(select auth.uid())
  and (public.is_admin() or public.has_location(location_id))
);

drop policy if exists weekly_evidences_update on public.weekly_evidences;
create policy weekly_evidences_update on public.weekly_evidences for update to authenticated
using (public.is_admin() or public.has_location(location_id))
with check (public.is_admin() or public.has_location(location_id));

create or replace function private.audit_weekly_evidence()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  actor uuid := (select auth.uid());
  actor_name text;
  actor_email text;
  local_name text;
begin
  select coalesce(nullif(trim(full_name),''),email),email
  into actor_name,actor_email
  from public.profiles where id=actor and active;
  if actor_email is null then
    raise exception 'Usuario no autorizado.' using errcode='42501';
  end if;

  if tg_op='INSERT' then
    select name into local_name from public.locations where id=new.location_id and active;
    if local_name is null then
      raise exception 'Local no disponible.' using errcode='23514';
    end if;
    new.location_name_snapshot:=local_name;
    new.submitted_by:=actor;
    new.submitted_by_name:=actor_name;
    new.submitted_by_email:=actor_email;
    new.submitted_at:=now();
  else
    new.location_id:=old.location_id;
    new.location_name_snapshot:=old.location_name_snapshot;
    new.week_start:=old.week_start;
    new.week_end:=old.week_end;
    new.evidence_type:=old.evidence_type;
    new.submitted_by:=old.submitted_by;
    new.submitted_by_name:=old.submitted_by_name;
    new.submitted_by_email:=old.submitted_by_email;
    new.submitted_at:=old.submitted_at;
  end if;

  new.last_updated_by:=actor;
  new.last_updated_by_name:=actor_name;
  new.updated_at:=now();
  return new;
end;
$$;
revoke all on function private.audit_weekly_evidence() from public, anon, authenticated;

drop trigger if exists audit_weekly_evidence on public.weekly_evidences;
create trigger audit_weekly_evidence before insert or update on public.weekly_evidences
for each row execute function private.audit_weekly_evidence();

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('weekly-evidence','weekly-evidence',false,8388608,array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set
  public=false,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists weekly_evidence_insert on storage.objects;
create policy weekly_evidence_insert on storage.objects for insert to authenticated
with check (
  bucket_id='weekly-evidence'
  and (storage.foldername(name))[1]=(select auth.uid())::text
  and private.is_active_user()
);

drop policy if exists weekly_evidence_select on storage.objects;
create policy weekly_evidence_select on storage.objects for select to authenticated
using (
  bucket_id='weekly-evidence'
  and (
    owner_id=(select auth.uid())::text
    or public.is_admin()
    or exists (
      select 1 from public.weekly_evidences evidence
      where evidence.evidence_path=name and public.has_location(evidence.location_id)
    )
  )
);
