-- Gestión semanal de rentabilidad y clientes de Región Sur.

create table if not exists public.regional_weekly_kpis (
  id bigint generated by default as identity primary key,
  week_start date not null,
  city text not null check (length(trim(city)) between 2 and 120),
  sales numeric(14,2) not null default 0 check (sales >= 0),
  orders integer not null default 0 check (orders >= 0),
  active_clients integer not null default 0 check (active_clients >= 0),
  average_ticket numeric(12,2) not null default 0 check (average_ticket >= 0),
  margin_percent numeric(7,2) not null default 0 check (margin_percent between -100 and 1000),
  late_percent numeric(7,2) not null default 0 check (late_percent between 0 and 100),
  rescheduling_percent numeric(7,2) not null default 0 check (rescheduling_percent between 0 and 100),
  oos_percent numeric(7,2) not null default 0 check (oos_percent between 0 and 100),
  incidents integer not null default 0 check (incidents >= 0),
  analysis text not null default '' check (length(analysis) <= 5000),
  affected_clients text not null default '' check (length(affected_clients) <= 5000),
  affected_sectors text not null default '' check (length(affected_sectors) <= 3000),
  action_plan text not null default '' check (length(action_plan) <= 5000),
  meeting_summary text not null default '' check (length(meeting_summary) <= 5000),
  created_by uuid not null references public.profiles(id),
  updated_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (week_start, city),
  constraint regional_weekly_kpis_monday_check check (extract(isodow from week_start)=1)
);

create table if not exists public.regional_meetings (
  id bigint generated by default as identity primary key,
  week_start date not null,
  meeting_date date not null,
  meeting_time time,
  meeting_type text not null check (meeting_type in ('individual','group','city')),
  title text not null check (length(trim(title)) between 3 and 180),
  participants text not null check (length(trim(participants)) between 2 and 2000),
  cities text not null default '' check (length(cities) <= 1000),
  topics text not null check (length(trim(topics)) between 3 and 5000),
  agreements text not null default '' check (length(agreements) <= 5000),
  responsible text not null default '' check (length(responsible) <= 1000),
  due_date date,
  status text not null default 'open' check (status in ('open','done')),
  evidence_paths text[] not null default '{}'::text[],
  created_by uuid not null references public.profiles(id),
  updated_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint regional_meetings_monday_check check (extract(isodow from week_start)=1),
  constraint regional_meetings_date_check check (meeting_date between week_start and week_start+6),
  constraint regional_meetings_evidence_check check (cardinality(evidence_paths) <= 10 and array_position(evidence_paths,null) is null)
);

create table if not exists public.regional_requests (
  id bigint generated by default as identity primary key,
  week_start date not null,
  city text not null check (length(trim(city)) between 2 and 120),
  target_area text not null check (target_area in ('marketing','b2b','commercial','operations','other')),
  request_text text not null check (length(trim(request_text)) between 3 and 5000),
  rationale text not null default '' check (length(rationale) <= 5000),
  priority text not null default 'medium' check (priority in ('low','medium','high')),
  responsible text not null default '' check (length(responsible) <= 1000),
  due_date date,
  status text not null default 'pending' check (status in ('pending','requested','in_progress','completed','rejected')),
  created_by uuid not null references public.profiles(id),
  updated_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint regional_requests_monday_check check (extract(isodow from week_start)=1)
);

create table if not exists public.regional_clients (
  id bigint generated by default as identity primary key,
  client_type text not null check (client_type in ('potential','blacklist')),
  client_external_id text not null check (length(trim(client_external_id)) between 1 and 120),
  client_name text not null check (length(trim(client_name)) between 2 and 200),
  city text not null check (length(trim(city)) between 2 and 120),
  sector text not null default '' check (length(sector) <= 500),
  estimated_orders integer check (estimated_orders is null or estimated_orders >= 0),
  responsible text not null default '' check (length(responsible) <= 500),
  observations text not null default '' check (length(observations) <= 5000),
  next_action text not null default '' check (length(next_action) <= 3000),
  next_action_date date,
  potential_status text not null default 'pending' check (potential_status in ('pending','contacted','interested','converted','discarded')),
  blacklist_reason text not null default '' check (length(blacklist_reason) <= 5000),
  order_reference text not null default '' check (length(order_reference) <= 200),
  evidence_paths text[] not null default '{}'::text[],
  blacklist_status text not null default 'pending' check (blacklist_status in ('pending','restricted','enabled','rejected')),
  submitted_by uuid not null references public.profiles(id),
  submitted_by_name text not null,
  approved_by uuid references public.profiles(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint regional_clients_evidence_check check (cardinality(evidence_paths) <= 10 and array_position(evidence_paths,null) is null),
  constraint regional_clients_blacklist_reason_check check (client_type='potential' or length(trim(blacklist_reason)) >= 3)
);

create index if not exists regional_weekly_kpis_week_idx on public.regional_weekly_kpis (week_start desc,city);
create index if not exists regional_weekly_kpis_created_by_idx on public.regional_weekly_kpis (created_by);
create index if not exists regional_weekly_kpis_updated_by_idx on public.regional_weekly_kpis (updated_by);
create index if not exists regional_meetings_week_idx on public.regional_meetings (week_start desc,meeting_date);
create index if not exists regional_meetings_created_by_idx on public.regional_meetings (created_by);
create index if not exists regional_meetings_updated_by_idx on public.regional_meetings (updated_by);
create index if not exists regional_requests_week_status_idx on public.regional_requests (week_start desc,status,city);
create index if not exists regional_requests_created_by_idx on public.regional_requests (created_by);
create index if not exists regional_requests_updated_by_idx on public.regional_requests (updated_by);
create index if not exists regional_clients_type_status_idx on public.regional_clients (client_type,blacklist_status,potential_status,city);
create index if not exists regional_clients_submitter_idx on public.regional_clients (submitted_by,created_at desc);
create index if not exists regional_clients_approved_by_idx on public.regional_clients (approved_by) where approved_by is not null;

alter table public.regional_weekly_kpis enable row level security;
alter table public.regional_meetings enable row level security;
alter table public.regional_requests enable row level security;
alter table public.regional_clients enable row level security;

revoke all on table public.regional_weekly_kpis,public.regional_meetings,public.regional_requests,public.regional_clients from anon,authenticated;
grant select,insert,update,delete on table public.regional_weekly_kpis,public.regional_meetings,public.regional_requests to authenticated;
grant select,insert,update,delete on table public.regional_clients to authenticated;
grant usage,select on sequence public.regional_weekly_kpis_id_seq,public.regional_meetings_id_seq,public.regional_requests_id_seq,public.regional_clients_id_seq to authenticated;

drop policy if exists regional_weekly_kpis_admin on public.regional_weekly_kpis;
create policy regional_weekly_kpis_admin on public.regional_weekly_kpis for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists regional_meetings_admin on public.regional_meetings;
create policy regional_meetings_admin on public.regional_meetings for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists regional_requests_admin on public.regional_requests;
create policy regional_requests_admin on public.regional_requests for all to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists regional_clients_read on public.regional_clients;
create policy regional_clients_read on public.regional_clients for select to authenticated
using ((select private.is_active_user()));

drop policy if exists regional_clients_insert on public.regional_clients;
create policy regional_clients_insert on public.regional_clients for insert to authenticated
with check ((select private.is_active_user()) and submitted_by=(select auth.uid()));

drop policy if exists regional_clients_update on public.regional_clients;
create policy regional_clients_update on public.regional_clients for update to authenticated
using ((select public.is_admin()) or submitted_by=(select auth.uid()))
with check ((select public.is_admin()) or submitted_by=(select auth.uid()));

drop policy if exists regional_clients_delete on public.regional_clients;
create policy regional_clients_delete on public.regional_clients for delete to authenticated
using ((select public.is_admin()));

create or replace function private.protect_regional_client()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $$
declare
  actor uuid:=(select auth.uid());
  actor_name text;
  actor_admin boolean;
begin
  select coalesce(nullif(trim(full_name),''),email),app_role='admin' and active
  into actor_name,actor_admin
  from public.profiles where id=actor and active;
  if actor_name is null then raise exception 'Usuario no autorizado.' using errcode='42501';end if;
  if tg_op='INSERT' then
    new.submitted_by:=actor;
    new.submitted_by_name:=actor_name;
    if new.client_type='blacklist' and not actor_admin then
      new.blacklist_status:='pending';new.approved_by:=null;new.approved_at:=null;
    elsif new.client_type='blacklist' and actor_admin and new.blacklist_status<>'pending' then
      new.approved_by:=actor;new.approved_at:=now();
    end if;
  else
    new.client_type:=old.client_type;
    new.client_external_id:=old.client_external_id;
    new.submitted_by:=old.submitted_by;
    new.submitted_by_name:=old.submitted_by_name;
    new.created_at:=old.created_at;
    if not actor_admin then
      new.blacklist_status:=old.blacklist_status;
      new.approved_by:=old.approved_by;
      new.approved_at:=old.approved_at;
    elsif new.client_type='blacklist' and new.blacklist_status is distinct from old.blacklist_status then
      new.approved_by:=actor;new.approved_at:=now();
    end if;
  end if;
  new.updated_at:=now();
  return new;
end;
$$;
revoke all on function private.protect_regional_client() from public,anon,authenticated;
drop trigger if exists protect_regional_client on public.regional_clients;
create trigger protect_regional_client before insert or update on public.regional_clients
for each row execute function private.protect_regional_client();

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('regional-evidence','regional-evidence',false,8388608,array['image/jpeg','image/png','image/webp','image/heic','image/heif'])
on conflict (id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists regional_evidence_insert on storage.objects;
create policy regional_evidence_insert on storage.objects for insert to authenticated
with check (
  bucket_id='regional-evidence'
  and (storage.foldername(name))[1]=(select auth.uid())::text
  and (select private.is_active_user())
);

drop policy if exists regional_evidence_select on storage.objects;
create policy regional_evidence_select on storage.objects for select to authenticated
using (
  bucket_id='regional-evidence'
  and (
    owner_id=(select auth.uid())::text
    or (select public.is_admin())
    or exists(select 1 from public.regional_clients client where name=any(client.evidence_paths))
  )
);
