create table if not exists public.administrator_evaluations (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete restrict,
  week_start date not null,
  week_end date not null,
  visit_date date not null,
  next_visit_date date,
  administrator_name text not null check (length(trim(administrator_name)) between 2 and 160),
  administrator_phone text not null default '',
  rule_compliance boolean,
  uniform_compliance boolean,
  ethics_compliance boolean,
  punctuality_compliance boolean,
  no_team_complaints boolean,
  particular_observations text not null default '',
  observations text not null default '',
  local_feedback text not null default '',
  supervisor_feedback text not null default '',
  submitted_by uuid not null,
  submitted_by_name text not null,
  submitted_by_email text not null,
  last_updated_by uuid not null,
  last_updated_by_name text not null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint administrator_evaluations_location_week_key unique (location_id, week_start),
  constraint administrator_evaluations_week_monday_check check (extract(isodow from week_start) = 1),
  constraint administrator_evaluations_week_end_check check (week_end = week_start + 6),
  constraint administrator_evaluations_visit_week_check check (visit_date between week_start and week_end),
  constraint administrator_evaluations_next_visit_check check (next_visit_date is null or next_visit_date >= visit_date)
);

comment on table public.administrator_evaluations is
  'Weekly administrator evaluations. Submitter names are immutable snapshots so account changes never rewrite history.';

create index if not exists administrator_evaluations_week_location_idx
  on public.administrator_evaluations (week_start, location_id);
create index if not exists administrator_evaluations_submitter_week_idx
  on public.administrator_evaluations (submitted_by, week_start desc);

create table if not exists public.administrator_evaluation_results (
  evaluation_id bigint primary key references public.administrator_evaluations(id) on delete cascade,
  compliant_count smallint not null check (compliant_count between 0 and 5),
  applicable_count smallint not null check (applicable_count between 1 and 5),
  score numeric(5,2) not null check (score between 0 and 100),
  semaphore text not null check (semaphore in ('green','yellow','red')),
  calculated_at timestamptz not null default now()
);

comment on table public.administrator_evaluation_results is
  'Private calculated results. Only the server-side service role can read or write this table.';

alter table public.administrator_evaluations enable row level security;
alter table public.administrator_evaluation_results enable row level security;

revoke all on table public.administrator_evaluations from anon, authenticated;
revoke all on table public.administrator_evaluation_results from anon, authenticated;
revoke all on sequence public.administrator_evaluations_id_seq from anon, authenticated;

grant select on table public.administrator_evaluations to authenticated;

drop policy if exists administrator_evaluations_read on public.administrator_evaluations;
create policy administrator_evaluations_read
on public.administrator_evaluations
for select
to authenticated
using (public.is_admin() or public.has_location(location_id));

-- Intentionally no client policies or grants exist for the private results table.
-- Writes and administrator result reads go through the authenticated server route.
