-- Registro semanal de nuevos clientes B2B para Región Sur.

create table if not exists public.b2b_client_contacts (
  id bigint generated by default as identity primary key,
  institution_type text not null check (institution_type in ('salud','ferreteria','papeleria','belleza','b2b')),
  institution_name text not null check (length(trim(institution_name)) between 2 and 200),
  contact_date date not null default current_date,
  sector text not null check (length(trim(sector)) between 2 and 300),
  contact_phone text not null default '' check (length(contact_phone) <= 80),
  email text not null default '' check (length(email) <= 320),
  store_names text[] not null default '{}'::text[],
  additional_comments text not null default '' check (length(additional_comments) <= 5000),
  contact_phone_normalized text generated always as (regexp_replace(contact_phone,'[^0-9]','','g')) stored,
  email_normalized text generated always as (lower(trim(email))) stored,
  submitted_by uuid not null references public.profiles(id),
  submitted_by_name text not null,
  submitted_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint b2b_client_contact_method_check check (
    length(regexp_replace(contact_phone,'[^0-9]','','g')) >= 7
    or lower(trim(email)) ~ '^[^@[:space:]]+@[^@[:space:]]+[.][^@[:space:]]+$'
  ),
  constraint b2b_client_contact_stores_check check (
    cardinality(store_names) <= 50 and array_position(store_names,null) is null
  )
);

create index if not exists b2b_client_contacts_date_idx
  on public.b2b_client_contacts (contact_date desc,institution_type);
create index if not exists b2b_client_contacts_submitter_idx
  on public.b2b_client_contacts (submitted_by,contact_date desc);
create unique index if not exists b2b_client_contacts_phone_unique
  on public.b2b_client_contacts (contact_phone_normalized)
  where length(contact_phone_normalized) >= 7;
create unique index if not exists b2b_client_contacts_email_unique
  on public.b2b_client_contacts (email_normalized)
  where email_normalized <> '';

alter table public.b2b_client_contacts enable row level security;
revoke all on table public.b2b_client_contacts from anon,authenticated;
grant select,insert,update,delete on table public.b2b_client_contacts to authenticated;
grant usage,select on sequence public.b2b_client_contacts_id_seq to authenticated;

drop policy if exists b2b_client_contacts_read on public.b2b_client_contacts;
create policy b2b_client_contacts_read on public.b2b_client_contacts
for select to authenticated
using ((select private.is_active_user()));

drop policy if exists b2b_client_contacts_insert on public.b2b_client_contacts;
create policy b2b_client_contacts_insert on public.b2b_client_contacts
for insert to authenticated
with check (
  (select private.is_active_user())
  and submitted_by=(select auth.uid())
);

drop policy if exists b2b_client_contacts_update on public.b2b_client_contacts;
create policy b2b_client_contacts_update on public.b2b_client_contacts
for update to authenticated
using (
  (select public.is_admin())
  or submitted_by=(select auth.uid())
)
with check (
  (select public.is_admin())
  or submitted_by=(select auth.uid())
);

drop policy if exists b2b_client_contacts_delete on public.b2b_client_contacts;
create policy b2b_client_contacts_delete on public.b2b_client_contacts
for delete to authenticated
using (
  (select public.is_admin())
  or submitted_by=(select auth.uid())
);

create or replace function private.protect_b2b_client_contact()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,public,private
as $$
declare
  actor uuid:=(select auth.uid());
  actor_name text;
  actor_email text;
begin
  select coalesce(nullif(trim(full_name),''),email),email
  into actor_name,actor_email
  from public.profiles
  where id=actor and active;

  if actor_name is null then
    raise exception 'Usuario no autorizado.' using errcode='42501';
  end if;

  if tg_op='INSERT' then
    new.submitted_by:=actor;
    new.submitted_by_name:=actor_name;
    new.submitted_by_email:=actor_email;
    new.created_at:=now();
  else
    new.submitted_by:=old.submitted_by;
    new.submitted_by_name:=old.submitted_by_name;
    new.submitted_by_email:=old.submitted_by_email;
    new.created_at:=old.created_at;
  end if;

  new.updated_at:=now();
  return new;
end;
$$;

revoke all on function private.protect_b2b_client_contact() from public,anon,authenticated;
drop trigger if exists protect_b2b_client_contact on public.b2b_client_contacts;
create trigger protect_b2b_client_contact
before insert or update on public.b2b_client_contacts
for each row execute function private.protect_b2b_client_contact();
